# Generated by Django 6.1 on 2026-10-05 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_detalleorden_precio_monedas_orden_total_monedas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monedero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoMonedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Positivo si suma al saldo, negativo si resta.')),
                ('tipo', models.CharField(choices=[('GANADA', 'Ganadas por una compra'), ('PAGO', 'Pago con monedas'), ('DEVOLUCION', 'Devolución de un pago con monedas'), ('RETIRO', 'Retiro de monedas ganadas (compra cancelada)'), ('AJUSTE', 'Ajuste manual del administrador')], max_length=20)),
                ('saldo_resultante', models.PositiveIntegerField(help_text='Saldo del usuario justo después de este movimiento.')),
                ('nota', models.CharField(blank=True, help_text='Motivo escrito por el admin en un ajuste manual.', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Admin que hizo el ajuste manual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, help_text='Orden que originó el movimiento (vacío en los ajustes manuales).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_monedas', to='orders.orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_monedas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de monedas',
                'verbose_name_plural': 'Movimientos de monedas',
                'ordering': ['-fecha', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('orden__isnull', False)), fields=('orden', 'tipo'), name='uniq_movimiento_monedas_orden_tipo')],
            },
        ),
    ]
