# Generated by Django 5.2.17 on 2026-08-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncargoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_requerimientos', models.TextField()),
                ('archivo_referencia', models.URLField(blank=True, help_text='Enlace externo a Google Drive, Dropbox o carpeta de imágenes con la referencia.', max_length=500, null=True)),
                ('estado_encargo', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Encargo Personalizado',
                'verbose_name_plural': 'Encargos Personalizados',
            },
        ),
    ]
