# Generated by Django 6.1 on 2026-09-03 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0003_initial'),
        ('orders', '0005_alter_orden_tipo_orden'),
        ('products', '0002_alter_producto_imagen_previa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Juego (Comisión de Modelo)',
                'verbose_name_plural': 'Juegos (Comisión de Modelo)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TramoPersonajesMotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: '1-3 Characters'", max_length=50)),
                ('min_personajes', models.PositiveIntegerField()),
                ('max_personajes', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden_visualizacion', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tramo de Personajes (Motion)',
                'verbose_name_plural': 'Tramos de Personajes (Motion)',
                'ordering': ['orden_visualizacion', 'min_personajes'],
            },
        ),
        migrations.CreateModel(
            name='ComisionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=150)),
                ('foto_referencia_1', models.ImageField(upload_to='comisiones/modelo/referencias/')),
                ('foto_referencia_2', models.ImageField(blank=True, null=True, upload_to='comisiones/modelo/referencias/')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('archivo_entrega', models.FileField(blank=True, null=True, upload_to='comisiones/modelo/')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_modelo', to='orders.orden')),
                ('producto_publicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comision_origen', to='products.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_modelo', to=settings.AUTH_USER_MODEL)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_orders.juegocomision')),
            ],
            options={
                'verbose_name': 'Comisión de Modelo Nuevo',
                'verbose_name_plural': 'Comisiones de Modelo Nuevo',
            },
        ),
        migrations.CreateModel(
            name='ComisionMotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=150)),
                ('nombre_cancion', models.CharField(max_length=150)),
                ('link_video', models.URLField(help_text='Video de referencia de la coreografía/canción.', max_length=500)),
                ('informacion_adicional', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('archivo_entrega', models.FileField(blank=True, null=True, upload_to='comisiones/motion/')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_motion', to='orders.orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_motion', to=settings.AUTH_USER_MODEL)),
                ('tramo_personajes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_orders.tramopersonajesmotion')),
            ],
            options={
                'verbose_name': 'Comisión de Motion',
                'verbose_name_plural': 'Comisiones de Motion',
            },
        ),
        migrations.DeleteModel(
            name='EncargoPersonalizado',
        ),
    ]
