# Generated by Django 6.1 on 2026-09-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0004_juegocomision_tramopersonajesmotion_comisionmodelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmodelo',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='comisiones/modelo/entrega/'),
        ),
    ]
