# Generated by Django 6.1 on 2026-09-11 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0005_comisionmodelo_foto_entrega'),
        ('products', '0004_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmodelo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categoria'),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categoria'),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='comisiones/motion/entrega/'),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='producto_publicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comision_motion_origen', to='products.producto'),
        ),
    ]
