# Generated by Django 6.1 on 2026-09-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0006_comisionmodelo_categoria_comisionmotion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramopersonajesmotion',
            name='nombre',
            field=models.CharField(help_text="Ej: 'Characters'", max_length=50),
        ),
    ]
