# Generated by Django 6.1 on 2026-09-17 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0007_restaurar_min_max_tramo'),
        ('products', '0006_agregar_categorias_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmodelo',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='comisiones_modelo_temp', to='products.categoria'),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='comisiones_motion_temp', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='comisionmodelo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_modelo_legacy', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='comisionmotion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_motion_legacy', to='products.categoria'),
        ),
    ]
