# Generated by Django 6.1 on 2026-09-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0009_migrar_categoria_a_categorias'),
        ('products', '0008_quitar_categoria_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionmodelo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comisionmotion',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='comisionmodelo',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='comisiones_modelo', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='comisionmotion',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='comisiones_motion', to='products.categoria'),
        ),
    ]
