# Generated by Django 6.1 on 2026-09-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0011_arreglar_comisiones_pagadas_en_cola'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmodelo',
            name='descripcion_publicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comisionmodelo',
            name='formato_archivo_publicacion',
            field=models.CharField(blank=True, help_text='Ej: STL, OBJ, FBX', max_length=50),
        ),
        migrations.AddField(
            model_name='comisionmodelo',
            name='link_youtube',
            field=models.URLField(blank=True, help_text='Link de YouTube con un video del resultado (opcional). Se copia al Producto al publicar.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comisionmodelo',
            name='precio_publicacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comisionmodelo',
            name='titulo_publicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='descripcion_publicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='formato_archivo_publicacion',
            field=models.CharField(blank=True, help_text='Ej: STL, OBJ, FBX', max_length=50),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='link_youtube',
            field=models.URLField(blank=True, help_text='Link de YouTube con un video del resultado (opcional). Se copia al Producto al publicar.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='precio_publicacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='titulo_publicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
