# Generated by Django 6.1 on 2026-10-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0012_datos_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmodelo',
            name='foto_entrega_miniatura',
            field=models.ImageField(blank=True, editable=False, help_text='Miniatura de foto_entrega; se genera sola.', null=True, upload_to='comisiones/miniaturas/'),
        ),
        migrations.AddField(
            model_name='comisionmodelo',
            name='foto_referencia_1_miniatura',
            field=models.ImageField(blank=True, editable=False, help_text='Miniatura de foto_referencia_1; se genera sola.', null=True, upload_to='comisiones/miniaturas/'),
        ),
        migrations.AddField(
            model_name='comisionmodelo',
            name='foto_referencia_2_miniatura',
            field=models.ImageField(blank=True, editable=False, help_text='Miniatura de foto_referencia_2; se genera sola.', null=True, upload_to='comisiones/miniaturas/'),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='foto_entrega_miniatura',
            field=models.ImageField(blank=True, editable=False, help_text='Miniatura de foto_entrega; se genera sola.', null=True, upload_to='comisiones/miniaturas/'),
        ),
    ]
