# Generated by Django 6.1 on 2026-10-05 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0013_miniaturas_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmodelo',
            name='precio_monedas_publicacion',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Precio en monedas. Vacío = no se puede pagar con monedas.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='precio_monedas_publicacion',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Precio en monedas. Vacío = no se puede pagar con monedas.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='juegocomision',
            name='precio_monedas',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Precio en monedas. Vacío = no se puede pagar con monedas.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tramopersonajesmotion',
            name='precio_monedas',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Precio en monedas. Vacío = no se puede pagar con monedas.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
