# Generated by Django 6.1 on 2026-10-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0014_comisionmodelo_precio_monedas_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmodelo',
            name='acepta_dinero_publicacion',
            field=models.BooleanField(db_index=True, default=True, help_text='Se puede comprar con dinero (carrito, Stripe o PayPal). Exige un precio en $.'),
        ),
        migrations.AddField(
            model_name='comisionmodelo',
            name='acepta_monedas_publicacion',
            field=models.BooleanField(db_index=True, default=False, help_text='Se puede pagar con MimiCoins. Exige un precio en MimiCoins.'),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='acepta_dinero_publicacion',
            field=models.BooleanField(db_index=True, default=True, help_text='Se puede comprar con dinero (carrito, Stripe o PayPal). Exige un precio en $.'),
        ),
        migrations.AddField(
            model_name='comisionmotion',
            name='acepta_monedas_publicacion',
            field=models.BooleanField(db_index=True, default=False, help_text='Se puede pagar con MimiCoins. Exige un precio en MimiCoins.'),
        ),
    ]
