# Generated by Django 5.2.17 on 2026-08-11 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio histórico al momento de la compra', max_digits=10)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(max_length=100, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('REEMBOLSADO', 'Reembolsado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('tipo_orden', models.CharField(choices=[('CATALOGO', 'Catálogo'), ('ENCARGO', 'Encargo Personalizado')], default='CATALOGO', max_length=20)),
                ('pasarela_pago', models.CharField(help_text='Ej: Stripe, PayPal', max_length=50)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(related_name='ordenes', through='orders.DetalleOrden', to='products.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.orden'),
        ),
        migrations.CreateModel(
            name='ComprasDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario conserva el permiso para descargar el archivo.')),
                ('fecha_adquisicion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprado_en', to='products.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_digitales', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(help_text='Orden de compra que respaldó este permiso de descarga.', on_delete=django.db.models.deletion.CASCADE, related_name='compras_digitales', to='orders.orden')),
            ],
            options={
                'verbose_name': 'Compra Digital',
                'verbose_name_plural': 'Compras Digitales',
                'db_table': 'compras_digitales',
                'unique_together': {('usuario', 'producto', 'orden')},
            },
        ),
    ]
