# Generated by Django 6.1 on 2026-08-16 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio histórico al momento de la compra', max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(max_length=100, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('REEMBOLSADO', 'Reembolsado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('tipo_orden', models.CharField(choices=[('CATALOGO', 'Catálogo'), ('ENCARGO', 'Encargo Personalizado')], default='CATALOGO', max_length=20)),
                ('pasarela_pago', models.CharField(help_text='Ej: Stripe, PayPal', max_length=50)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.CreateModel(
            name='ComprasDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario conserva el permiso para descargar el archivo.')),
                ('fecha_adquisicion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprado_en', to='products.producto')),
            ],
            options={
                'verbose_name': 'Compra Digital',
                'verbose_name_plural': 'Compras Digitales',
                'db_table': 'compras_digitales',
            },
        ),
    ]
