# Generated by Django 6.1 on 2026-08-16 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasdigitales',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_digitales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producto'),
        ),
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(related_name='ordenes', through='orders.DetalleOrden', to='products.producto'),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.orden'),
        ),
        migrations.AddField(
            model_name='comprasdigitales',
            name='orden',
            field=models.ForeignKey(help_text='Orden de compra que respaldó este permiso de descarga.', on_delete=django.db.models.deletion.CASCADE, related_name='compras_digitales', to='orders.orden'),
        ),
        migrations.AlterUniqueTogether(
            name='comprasdigitales',
            unique_together={('usuario', 'producto', 'orden')},
        ),
    ]
