# Generated by Django 6.1 on 2026-08-23 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0002_alter_producto_imagen_previa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comprasdigitales',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comprasdigitales',
            name='fecha_revocacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprasdigitales',
            name='motivo_revocacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comprasdigitales',
            name='orden',
            field=models.ForeignKey(help_text='Orden de compra que respaldó este permiso de descarga.', on_delete=django.db.models.deletion.PROTECT, related_name='compras_digitales', to='orders.orden'),
        ),
        migrations.AlterField(
            model_name='comprasdigitales',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprado_en', to='products.producto'),
        ),
        migrations.AddIndex(
            model_name='comprasdigitales',
            index=models.Index(fields=['usuario', 'activo'], name='compras_dig_usuario_4ab986_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprasdigitales',
            constraint=models.UniqueConstraint(fields=('usuario', 'producto', 'orden'), name='uniq_compra_producto'),
        ),
    ]
