# Generated by Django 6.1 on 2026-08-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_comprasdigitales_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='ID de la Stripe Checkout Session que respalda esta orden.', max_length=255, null=True, unique=True),
        ),
    ]
