# Generated by Django 6.1 on 2026-09-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orden_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tipo_orden',
            field=models.CharField(choices=[('CATALOGO', 'Catálogo'), ('COMISION_MOTION', 'Comisión de Motion'), ('COMISION_MODELO', 'Comisión de Modelo Nuevo')], default='CATALOGO', max_length=20),
        ),
    ]
