# Generated by Django 6.1 on 2026-09-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orden_tipo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='paypal_order_id',
            field=models.CharField(blank=True, help_text='ID de la orden de PayPal que respalda esta orden.', max_length=255, null=True, unique=True),
        ),
    ]
