# Generated by Django 6.1 on 2026-10-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orden_paypal_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='precio_monedas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='total_monedas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='pasarela_pago',
            field=models.CharField(help_text='Ej: Stripe, PayPal, Monedas', max_length=50),
        ),
    ]
