# Generated by Django 5.2.17 on 2026-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='admin_ultimo_leido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='cliente_ultimo_leido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
