# Generated by Django 6.1 on 2026-08-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formato_archivo', models.CharField(help_text='Ej: STL, OBJ, FBX', max_length=50)),
                ('archivo_3d', models.FileField(upload_to='modelos_3d/')),
                ('imagen_previa', models.URLField(blank=True, help_text='URL de la imagen de previsualización (Ej: Supabase Storage / S3)', max_length=500, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
