# Generated by Django 6.1 on 2026-08-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_previa',
            field=models.ImageField(blank=True, help_text='Imagen de previsualización del producto.', null=True, upload_to='productos_preview/'),
        ),
    ]
