# Generated by Django 6.1 on 2026-09-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producto_imagen_previa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link_youtube',
            field=models.URLField(blank=True, help_text='Link de YouTube con un video de vista previa del modelo (opcional).', max_length=500, null=True),
        ),
    ]
