# Generated by Django 6.1 on 2026-09-17 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categoria_nombre_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(related_name='productos_temp', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_legacy', to='products.categoria'),
        ),
    ]
