# Generated by Django 6.1 on 2026-09-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_migrar_categoria_a_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(related_name='productos', to='products.categoria'),
        ),
    ]
