# Generated by Django 6.1 on 2026-09-20 20:30

from django.db import migrations, models

from core.text_utils import normalizar_texto


def rellenar_campos_normalizados(apps, schema_editor):
    # Los productos ya existentes no pasaron por Producto.save(), así que sus
    # columnas normalizadas nacen vacías y la búsqueda no los encontraría.
    Producto = apps.get_model('products', 'Producto')
    for producto in Producto.objects.all().iterator():
        producto.titulo_normalizado = normalizar_texto(producto.titulo)
        producto.descripcion_normalizada = normalizar_texto(producto.descripcion)
        producto.save(update_fields=['titulo_normalizado', 'descripcion_normalizada'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_quitar_categoria_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion', '-id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_normalizada',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo_normalizado',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.RunPython(rellenar_campos_normalizados, migrations.RunPython.noop),
    ]
