# Generated by Django 6.1 on 2026-10-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, editable=False, help_text='Miniatura de la imagen de previsualización; se genera sola.', null=True, upload_to='productos_miniaturas/'),
        ),
    ]
