# Generated by Django 6.1 on 2026-10-05 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_producto_imagen_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_monedas',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Precio en monedas. Vacío = no se puede pagar con monedas.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
