# Generated by Django 6.1 on 2026-10-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_producto_precio_monedas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='acepta_dinero',
            field=models.BooleanField(db_index=True, default=True, help_text='Se puede comprar con dinero (carrito, Stripe o PayPal). Exige un precio en $.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='acepta_monedas',
            field=models.BooleanField(db_index=True, default=False, help_text='Se puede pagar con MimiCoins. Exige un precio en MimiCoins.'),
        ),
    ]
