# Generated by Django 6.1 on 2026-10-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Idioma en que el usuario usa el sitio; en él se le escriben los correos. Se actualiza solo (users/authentication.py), no se edita a mano.', max_length=2),
        ),
    ]
