# Generated by Django 6.1 on 2026-10-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil, ya recortada y reducida (ver users/perfil.py).', null=True, upload_to='perfiles/'),
        ),
    ]
