# Generated by Django 6.1 on 2026-10-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_hash', models.CharField(help_text='Huella (HMAC-SHA256) del código; el código en claro nunca se guarda.', max_length=64)),
                ('enviado_en', models.DateTimeField()),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0, help_text='Intentos fallidos con este código.')),
                ('verificado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Código de verificación de correo',
                'verbose_name_plural': 'Códigos de verificación de correo',
            },
        ),
    ]
